2024-05-07 14:33:17,384 INFO    StreamThr :3071832 [internal.py:wandb_internal():86] W&B internal server running at pid: 3071832, started at: 2024-05-07 14:33:17.381198
2024-05-07 14:33:17,392 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: status
2024-05-07 14:33:17,393 INFO    WriterThread:3071832 [datastore.py:open_for_write():87] open: /project/dfreedman/hackathon/molecular_nexus/ai-sci-hackathon-2024-molecular-nexus/wandb/run-20240507_143317-baw637ix/run-baw637ix.wandb
2024-05-07 14:33:17,396 DEBUG   SenderThread:3071832 [sender.py:send():379] send: header
2024-05-07 14:33:17,433 DEBUG   SenderThread:3071832 [sender.py:send():379] send: run
2024-05-07 14:33:22,434 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: keepalive
2024-05-07 14:33:27,435 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: keepalive
2024-05-07 14:33:32,437 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: keepalive
2024-05-07 14:33:37,438 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: keepalive
2024-05-07 14:33:42,440 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: keepalive
2024-05-07 14:33:47,441 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: keepalive
2024-05-07 14:33:52,442 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: keepalive
2024-05-07 14:33:57,444 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: keepalive
2024-05-07 14:34:02,445 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: keepalive
2024-05-07 14:34:07,446 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: keepalive
2024-05-07 14:34:12,448 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: keepalive
2024-05-07 14:34:17,449 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: keepalive
2024-05-07 14:34:20,926 INFO    SenderThread:3071832 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f43cc39d640>, 'Connection to api.wandb.ai timed out. (connect timeout=20)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f43cc39d640>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f43cc39d640>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))
2024-05-07 14:34:25,519 DEBUG   HandlerThread:3071832 [handler.py:handle_request():146] handle_request: shutdown
2024-05-07 14:34:25,520 INFO    HandlerThread:3071832 [handler.py:finish():866] shutting down handler
2024-05-07 14:34:26,443 INFO    WriterThread:3071832 [datastore.py:close():296] close: /project/dfreedman/hackathon/molecular_nexus/ai-sci-hackathon-2024-molecular-nexus/wandb/run-20240507_143317-baw637ix/run-baw637ix.wandb
