2024-05-07 14:13:10,834 INFO    MainThread:3062108 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-07 14:13:10,834 INFO    MainThread:3062108 [wandb_setup.py:_flush():76] Configure stats pid to 3062108
2024-05-07 14:13:10,835 INFO    MainThread:3062108 [wandb_setup.py:_flush():76] Loading settings from /home/rzhu16/.config/wandb/settings
2024-05-07 14:13:10,835 INFO    MainThread:3062108 [wandb_setup.py:_flush():76] Loading settings from /project/dfreedman/hackathon/molecular_nexus/ai-sci-hackathon-2024-molecular-nexus/wandb/settings
2024-05-07 14:13:10,835 INFO    MainThread:3062108 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-07 14:13:10,835 INFO    MainThread:3062108 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-07 14:13:10,835 INFO    MainThread:3062108 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': '1_force_field_parameter_prediction.py', 'program_abspath': '/project/dfreedman/hackathon/molecular_nexus/ai-sci-hackathon-2024-molecular-nexus/1_force_field_parameter_prediction.py', 'program': '/project/dfreedman/hackathon/molecular_nexus/ai-sci-hackathon-2024-molecular-nexus/1_force_field_parameter_prediction.py'}
2024-05-07 14:13:10,835 INFO    MainThread:3062108 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-07 14:13:10,835 INFO    MainThread:3062108 [wandb_init.py:_log_setup():521] Logging user logs to /project/dfreedman/hackathon/molecular_nexus/ai-sci-hackathon-2024-molecular-nexus/wandb/run-20240507_141310-q5mxdwv4/logs/debug.log
2024-05-07 14:13:10,835 INFO    MainThread:3062108 [wandb_init.py:_log_setup():522] Logging internal logs to /project/dfreedman/hackathon/molecular_nexus/ai-sci-hackathon-2024-molecular-nexus/wandb/run-20240507_141310-q5mxdwv4/logs/debug-internal.log
2024-05-07 14:13:10,835 INFO    MainThread:3062108 [wandb_init.py:init():561] calling init triggers
2024-05-07 14:13:10,836 INFO    MainThread:3062108 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-05-07 14:13:10,836 INFO    MainThread:3062108 [wandb_init.py:init():611] starting backend
2024-05-07 14:13:10,836 INFO    MainThread:3062108 [wandb_init.py:init():615] setting up manager
2024-05-07 14:13:10,838 INFO    MainThread:3062108 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-07 14:13:10,847 INFO    MainThread:3062108 [wandb_init.py:init():623] backend started and connected
2024-05-07 14:13:10,854 INFO    MainThread:3062108 [wandb_init.py:init():715] updated telemetry
2024-05-07 14:13:10,956 INFO    MainThread:3062108 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-05-07 14:14:08,370 WARNING MainThread:3062108 [wandb_init.py:init():1203] interrupted
Traceback (most recent call last):
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 751, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-05-07 14:14:09,384 INFO    Thread-1 (wrapped_target):3062108 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f6d91d970b0>, 'Connection to api.wandb.ai timed out. (connect timeout=20)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6d91d970b0>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/dfreedman/hackathon/molecular_nexus/conda_env/AI4Science_hackathon/lib/python3.12/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6d91d970b0>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))
